Classes = [
    {
        'cid': '{5ef66ec6-8c35-4f37-923d-74bfc7e0a6a3}',
        'contract_ids': ['@mozdevgroup.com/openkioskdom;1'],
        'jsm': 'resource:///modules/OpenKioskDOM.jsm',
        'constructor': 'OpenKiosk',
    },
]

