  <!-- OSK -->
  <vbox id="ok-osk-main">
    <html:div id="ok-osk" class="keyboard keyboard-hidden">
      <html:div id="osk-main-keys" class="keyboard_keys top">
        <html:div class="keyboard_key">q</html:div>
        <html:div class="keyboard_key">w</html:div>
        <html:div class="keyboard_key">e</html:div>
        <html:div class="keyboard_key">r</html:div>
        <html:div class="keyboard_key">t</html:div>
        <html:div class="keyboard_key">y</html:div>
        <html:div class="keyboard_key">u</html:div>
        <html:div class="keyboard_key">i</html:div>
        <html:div class="keyboard_key">o</html:div>
        <html:div class="keyboard_key">p</html:div>
        <html:div id="osk-bs" class="keyboard_key keyboard_key-wide"><html:i class="material-icons">backspace</html:i></html:div>
        <html:br/>
        <html:div id="osk-caps" class="keyboard_key keyboard_key-wide keyboard_key-activatable"><html:i class="material-icons">keyboard_capslock</html:i></html:div>
        <html:div class="keyboard_key">a</html:div>
        <html:div class="keyboard_key">s</html:div>
        <html:div class="keyboard_key">d</html:div>
        <html:div class="keyboard_key">f</html:div>
        <html:div class="keyboard_key">g</html:div>
        <html:div class="keyboard_key">h</html:div>
        <html:div class="keyboard_key">j</html:div>
        <html:div class="keyboard_key">k</html:div>
        <html:div class="keyboard_key">l</html:div>
        <html:div class="keyboard_key keyboard_key-wide"><html:i class="material-icons">keyboard_return</html:i></html:div>
        <html:br/>
        <html:div class="keyboard_key"><html:i class="material-icons">keyboard_hide</html:i></html:div>
        <html:div class="keyboard_key">z</html:div>
        <html:div class="keyboard_key">x</html:div>
        <html:div class="keyboard_key">c</html:div>
        <html:div class="keyboard_key">v</html:div>
        <html:div class="keyboard_key">b</html:div>
        <html:div class="keyboard_key">n</html:div>
        <html:div class="keyboard_key">m</html:div>
        <html:div class="keyboard_key">@</html:div>
        <html:div class="keyboard_key">/</html:div>
        <html:div class="keyboard_key"><html:i class="material-icons">keyboard_alt</html:i></html:div>
        <html:br/>
        <html:div class="keyboard_key">.org</html:div>
        <html:div class="keyboard_key keyboard_key-extra-wide"><html:i class="material-icons">space_bar</html:i></html:div>
        <html:div class="keyboard_key">.com</html:div>
      </html:div>
      <html:div id="osk-alt-keys" class="keyboard_keys keyboard-hidden bottom">
        <html:div class="keyboard_key">1</html:div>
        <html:div class="keyboard_key">2</html:div>
        <html:div class="keyboard_key">3</html:div>
        <html:div class="keyboard_key">4</html:div>
        <html:div class="keyboard_key">5</html:div>
        <html:div class="keyboard_key">6</html:div>
        <html:div class="keyboard_key">7</html:div>
        <html:div class="keyboard_key">8</html:div>
        <html:div class="keyboard_key">9</html:div>
        <html:div class="keyboard_key">0</html:div>
        <html:div class="keyboard_key keyboard_key-wide"><html:i class="material-icons">clear</html:i></html:div>
        <html:br/>
        <html:div class="keyboard_key">`</html:div>
        <html:div class="keyboard_key">|</html:div>
        <html:div class="keyboard_key">{</html:div>
        <html:div class="keyboard_key">}</html:div>
        <html:div class="keyboard_key">%</html:div>
        <html:div class="keyboard_key">^</html:div>
        <html:div class="keyboard_key">*</html:div>
        <html:div class="keyboard_key">-</html:div>
        <html:div class="keyboard_key">'</html:div>
        <html:div class="keyboard_key">?</html:div>
        <html:div class="keyboard_key keyboard_key-wide"><html:i class="material-icons">keyboard_return</html:i></html:div>
        <html:br/>
        <html:div class="keyboard_key">&amp;</html:div>
        <html:div class="keyboard_key">~</html:div>
        <html:div class="keyboard_key">#</html:div>
        <html:div class="keyboard_key">=</html:div>
        <html:div class="keyboard_key">+</html:div>
        <html:div class="keyboard_key">!</html:div>
        <html:div class="keyboard_key">$</html:div>
        <html:div class="keyboard_key">_</html:div>
        <html:div class="keyboard_key">.</html:div>
        <html:div class="keyboard_key">"</html:div>
        <html:div class="keyboard_key"><html:i class="material-icons">keyboard</html:i></html:div>
        <html:br/>
        <html:div class="keyboard_key keyboard_key-extra-wide"><html:i class="material-icons">space_bar</html:i></html:div>
      </html:div>
    </html:div>
  </vbox>
