        <toolbarbutton id="ok-reset-button" class="toolbarbutton-1 chromeclass-toolbar-additional"
                       removable="true"
                       data-l10n-id="navbar-ok-reset-button"
                       cui-areatype="toolbar"
                       oncommand="OpenKioskSession.manualReset();" />

        <toolbarbutton id="ok-quit-button" class="toolbarbutton-1 chromeclass-toolbar-additional"
                       removable="true"
                       data-l10n-id="navbar-ok-quit-button"
                       cui-areatype="toolbar"
                       oncommand="OpenKioskAdmin.quitFromButton();" />

        <toolbarbutton id="ok-settings-button" class="toolbarbutton-1 chromeclass-toolbar-additional"
                       removable="true"
                       data-l10n-id="navbar-ok-settings-button"
                       cui-areatype="toolbar"
                       oncommand="OpenKioskAdmin.prompt();" />
